document = { stmt, '\n', '\n', { '\n' }}, [ stmt ], { '\n' }, ?EOF?;
stmt = (expr, { '\n', expr }) | curly;
expr = (text | square | angle), {text | square | angle};

angle = '<', [(module | angle), '.'], (ident | angle), [argument, {',', argument}], '>';
square = '[', [(module | angle), '.'], (ident | angle), [argument, {',', argument}], ']';
curly = '{', [(module | angle), '.'], (ident | angle), [argument, {',', argument}], '}';

argument = expr | string_literal | number_literal | boolean_literal | url_literal | path_literal | list_literal | tuple_literal | record_literal;
item = text | string | number | boolean | url | path | list_literal | tuple_literal | record_literal;

string_literal = '"', ? ダブルクォーテーションを含まない任意の文字列 ?, '"';
number_literal = '(', number, ')';
boolean_literal = '(', boolean, ')';
url_literal = '(', url, ')';
path_literal = '(', path, ')';
list_literal = '#', '(', {item}, ')';
tuple_literal = '!', '(', {item}, ')';
record_literal = '(', {string, ':', (string | number | boolean | url | path)}, ')';

module = string;
ident = string;

text = ? all character ?;
string = ? [^\[\{\<\(\.,\s#!\\] ?;
number = ? [0-9]+ ?;
boolean = 'true' | 'false';
url = ? url ?;
path = ? absolute or relative path ?;
