document = { stmt, '\n', '\n', { '\n' }}, [ stmt ], { '\n' }, ?EOF?;
stmt = (expr, { '\n', expr }) | curly;
expr = (text_expr | square), {text_expr | square};

square = '[',
        [module, '.'], ident,
        [
            argument, {',', argument}
            | argument, {',', argument}, ',', argument_with_name, {',', argument_with_name}
            | argument_with_name, {',', argument_with_name}
        ],
    ']';

curly = '{',
        [module, '.'], ident,
        [
            argument, {',', argument}
            | argument, {',', argument}, ',', argument_with_name, {',', argument_with_name}
            | argument_with_name, {',', argument_with_name}
        ],
    '}';

argument_with_name = word, '=', argument;
argument = (text_argument | square), {text_argument | square}
    | string_literal
    | int_literal
    | float_literal
    | boolean_literal
    | list
    | tuple
    | record;

item = string
    | int
    | float
    | boolean
    | list
    | tuple
    | record
    | square;

string_literal = '(', string, ')';
int_literal = '(', int, ')';
float_literal = '(', float, ')';
boolean_literal = '(', boolean, ')';
list = '@', '(', [item, {',', item}],')';
tuple = '!', '(', [item, {',', item}], ')';
record = '#', '(', [word, ':', item, {',', word, ':', item}], ')';

module = word;
ident = word;

text_expr = ? [^\[\{<\]\}<\n]+ ?; (* コマンドを呼び出せるbracktおよび改行以外の任意の文字列 *)
text_argument = ? [^,=\[\{<\(\]\}\)<\n]+ ?; (* カンマと各種bracket以外からなる任意の文字列 *)
word = ? [^\.,:=\[\{<\(\]\}>\)\s]+ ?; (* ドット、カンマ、コロン、各種ブラケット、空白以外からなる任意の文字列 *)
string = '"', ? ([^"] | \\")+ ?, '"' | "'", ? ([^'] | \\')+ ?, "'" ; (* エスケープされていないクォーテーションを含まない任意の文字列 *)
int = ? -[1-9][0-9]* | [0-9]+ ?;
float = ? (-|)[0-9]+\.[0-9]+ ?;
boolean = 'true' | 'false';
