document       = stmt*
stmt           = block_command | expr_seq "\n"*
expr_seq       = expr ("\n" expr)*
expr           = (commandable | inline_command)+
commandable    = (text | macro_command)+
macro_command  = "<" command_spec ">"
block_command  = "{" command_spec "}"
inline_command = "[" command_spec "]"
command_spec   = commandable (" " arguments)?
arguments      = expr ("," expr)*
text           = character+
character      = LETTER
