document := (stmt newline newline+)* stmt? newline* EOF
stmt := expr (newline expr)*
expr := (text | square | angle)+
angle := angle_bracket_open (module | angle) dot (ident | angle) (expr (comma expr)*)? angle_bracket_close 
curly := curly_bracket_open (module | angle) dot (ident | angle) (expr (comma expr)*)? curly_bracket_close
square := square_bracket_open (module | angle) dot (ident | angle) (expr (comma expr)*)? square_bracket_close
angle_bracket_open := "<"
angle_bracket_close := ">"
square_bracket_open := "["
square_bracket_close := "]"
curly_bracket_open := "{"
curly_bracket_close := "}"
module := text
ident := text
text := [^.]+
whitespace := " "
newline := "\n"
dot := "."
comma := ","
