document := (stmt (newline+ | newline* EOF))*
stmt := expr (newline expr)*
expr := (whitespace | newline)* (text | module | ident | bracket)* (whitespace | newline)*
bracket := bracket_open expr dot? expr (expr (comma expr)*)? bracket_close?
bracket_open := (angle_bracket_open | square_bracket_open | curly_bracket_open)
bracket_close := (angle_bracket_close | square_bracket_close | curly_bracket_close)
angle_bracket_open := "<"
angle_bracket_close := ">"
square_bracket_open := "["
square_bracket_close := "]"
curly_bracket_open := "{"
curly_bracket_close := "}"
module := text
ident := text
text := [^.]+
whitespace := " "
newline := "\n"
dot = "."
comma := ","
