[workspace]

members = [
    "brack",
    "brack-codegen",
    "brack-expander",
    "brack-language-server",
    "brack-parser",
    "brack-plugin",
    "brack-plugin-manager",
    "brack-tokenizer",
]

resolver = "2"
