[package]
name = "brack"
version = "0.2.0"
edition = "2021"
authors = [
    "Mutsuha Asada <me@momee.mt>",
    "Kanta Ueno <kantaueno0808@yahoo.co.jp>",
]
description = "A bracket-based lightweight markup language that extends commands with WebAssembly"

[dependencies]
brack-common = { git = "https://github.com/brack-lang/brack", package = "brack-common" }
brack-project = { git = "https://github.com/brack-lang/brack", package = "brack-project" }
tokio = { version = "1", features = ["full"] }
anstyle = "1.0.11"
colored = "3.0.0"
codespan-reporting = "0.12.0"
file-size = "1.0.3"

[dependencies.clap]
version = "4.5.40"
features = ["derive"]

[features]
default = []
debug = []

[workspace]
members = [
    "crates/brack-codegen",
    "crates/brack-common",
    "crates/brack-expander",
    "crates/brack-language-server",
    "crates/brack-parser",
    "crates/brack-plugin",
    "crates/brack-project",
    "crates/brack-release",
    "crates/brack-tokenizer",
    "crates/brack-transformer",
]

resolver = "2"

[patch."https://github.com/brack-lang/brack"]
brack-codegen = { path = "crates/brack-codegen" }
brack-common = { path = "crates/brack-common" }
brack-expander = { path = "crates/brack-expander" }
brack-language-server = { path = "crates/brack-language-server" }
brack-parser = { path = "crates/brack-parser" }
brack-plugin = { path = "crates/brack-plugin" }
brack-project = { path = "crates/brack-project" }
brack-tokenizer = { path = "crates/brack-tokenizer" }
brack-transformer = { path = "crates/brack-transformer" }
