[package]
name = "brack-transformer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brack-common = { git = "https://github.com/brack-lang/brack", package = "brack-common" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.12"

[features]
default = []
debug = []

[[bin]]
name = "debug_compile"
path = "src/debug/debug_compile.rs"
required-features = ["debug"]
