use crate::location::Location;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Token {
    Empty(Location),
    Text(String, Location),
    Ident(String, Location),
    AngleBracketOpen(Location),
    AngleBracketClose(Location),
    SquareBracketOpen(Location),
    SquareBracketClose(Location),
    CurlyBracketOpen(Location),
    CurlyBracketClose(Location),
    ParenthesisOpen(Location),
    ParenthesisClose(Location),
    NewLine(Location),
    WhiteSpace(Location),
    Dot(Location),
    SingleQuote(Location),
    DoubleQuote(Location),
    BackSlash(Location),
    Comma(Location),
    Equals(Location),
    Colon(Location),
    At(Location),
    Exclamation(Location),
    Hash(Location),
    String(String, Location),
    Number(String, Location),
    Boolean(bool, Location),
    EOF(Location),
}

impl Token {
    pub fn get_location(&self) -> Location {
        match self {
            Token::Empty(location) => location.clone(),
            Token::Text(_, location) => location.clone(),
            Token::Ident(_, location) => location.clone(),
            Token::AngleBracketOpen(location) => location.clone(),
            Token::AngleBracketClose(location) => location.clone(),
            Token::SquareBracketOpen(location) => location.clone(),
            Token::SquareBracketClose(location) => location.clone(),
            Token::CurlyBracketOpen(location) => location.clone(),
            Token::CurlyBracketClose(location) => location.clone(),
            Token::ParenthesisOpen(location) => location.clone(),
            Token::ParenthesisClose(location) => location.clone(),
            Token::NewLine(location) => location.clone(),
            Token::WhiteSpace(location) => location.clone(),
            Token::Dot(location) => location.clone(),
            Token::SingleQuote(location) => location.clone(),
            Token::DoubleQuote(location) => location.clone(),
            Token::BackSlash(location) => location.clone(),
            Token::Comma(location) => location.clone(),
            Token::Equals(location) => location.clone(),
            Token::Colon(location) => location.clone(),
            Token::At(location) => location.clone(),
            Token::Exclamation(location) => location.clone(),
            Token::Hash(location) => location.clone(),
            Token::String(_, location) => location.clone(),
            Token::Number(_, location) => location.clone(),
            Token::Boolean(_, location) => location.clone(),
            Token::EOF(location) => location.clone(),
        }
    }

    pub fn set_location(&mut self, location: Location) {
        match self {
            Token::Empty(l) => *l = location,
            Token::Text(_, l) => *l = location,
            Token::Ident(_, l) => *l = location,
            Token::AngleBracketOpen(l) => *l = location,
            Token::AngleBracketClose(l) => *l = location,
            Token::SquareBracketOpen(l) => *l = location,
            Token::SquareBracketClose(l) => *l = location,
            Token::CurlyBracketOpen(l) => *l = location,
            Token::CurlyBracketClose(l) => *l = location,
            Token::ParenthesisOpen(l) => *l = location,
            Token::ParenthesisClose(l) => *l = location,
            Token::NewLine(l) => *l = location,
            Token::WhiteSpace(l) => *l = location,
            Token::Dot(l) => *l = location,
            Token::SingleQuote(l) => *l = location,
            Token::DoubleQuote(l) => *l = location,
            Token::BackSlash(l) => *l = location,
            Token::Comma(l) => *l = location,
            Token::Equals(l) => *l = location,
            Token::Colon(l) => *l = location,
            Token::At(l) => *l = location,
            Token::Exclamation(l) => *l = location,
            Token::Hash(l) => *l = location,
            Token::String(_, l) => *l = location,
            Token::Number(_, l) => *l = location,
            Token::Boolean(_, l) => *l = location,
            Token::EOF(l) => *l = location,
        }
    }
}
