name: CI
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE*'
      - 'brack.*.ebnf'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE*'
      - 'brack.*.ebnf'
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --all-systems
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .
  cargo-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#cargo-fmt"
  clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix profile install "nixpkgs#rustc" "nixpkgs#cargo" "nixpkgs#clippy"
      - uses: actions-rs/clippy-check@v1
        env:
          CARGO_HOME: ./.cargo
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          args: -- -D warnings
  nixfmt-rfc-style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#nixfmt-rfc-style"

