name: CI
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE*'
      - 'brack.*.ebnf'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE*'
      - 'brack.*.ebnf'
      - '**/*.md'

jobs:
  flake-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --all-systems
  build-x86_64-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#packages.x86_64-linux.default"
  build-x86_64-darwin:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#packages.x86_64-darwin.default"
  build-aarch64-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#packages.aarch64-darwin.default"
