name: main
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log-in to GitHub
        run: |
          nix profile install nixpkgs#gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Get current version
        id: version
        run: |
          echo "version=$(cat ./VERSION)" >> $GITHUB_OUTPUT
      - name: Generate release note
        id: release-note
        run: |
          bash scripts/release-note.sh v${{ steps.version.outputs.version }} 2>/dev/null | tee release_notes.md
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false

