name: release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Get current version
        id: version
        run: |
          echo "version=$(cat ./VERSION)" >> $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') }}
          generate_release_notes: true

