name: release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#packages.x86_64-linux.brack"
      - uses: actions/upload-artifact@v4
        with:
          name: brack-x86_64-linux
          path: result/bin/brack
      - uses: actions/upload-artifact@v4
        with:
          name: brack-release-x86_64-linux
          path: result/bin/brack-release
  
  build-x86_64-darwin:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#packages.x86_64-darwin.brack"
      - uses: actions/upload-artifact@v4
        with:
          name: brack-x86_64-darwin
          path: result/bin/brack
      - uses: actions/upload-artifact@v4
        with:
          name: brack-release-x86_64-darwin
          path: result/bin/brack-release

  build-aarch64-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: brack-lang
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#packages.aarch64-darwin.brack"
      - uses: actions/upload-artifact@v4
        with:
          name: brack-aarch64-darwin
          path: result/bin/brack
      - uses: actions/upload-artifact@v4
        with:
          name: brack-release-aarch64-darwin
          path: result/bin/brack-release

  tag:
    runs-on: ubuntu-24.04
    needs: [ build-x86_64-linux, build-x86_64-darwin, build-aarch64-darwin ]
    steps:
      - uses: actions/checkout@v4
      - name: Get current version
        id: version
        run: |
          echo "version=$(cat ./VERSION)" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          name: brack-x86_64-linux
          path: x86_64-linux
      - uses: actions/download-artifact@v4
        with:
          name: brack-release-x86_64-linux
          path: x86_64-linux
      - uses: actions/download-artifact@v4
        with:
          name: brack-x86_64-darwin
          path: x86_64-darwin
      - uses: actions/download-artifact@v4
        with:
          name: brack-release-x86_64-darwin
          path: x86_64-darwin
      - uses: actions/download-artifact@v4
        with:
          name: brack-aarch64-darwin
          path: aarch64-darwin
      - uses: actions/download-artifact@v4
        with:
          name: brack-release-aarch64-darwin
          path: aarch64-darwin
      - run: |
          mv x86_64-linux/brack x86_64-linux/brack-x86_64-linux
          mv x86_64-linux/brack-release x86_64-linux/brack-release-x86_64-linux
          mv x86_64-darwin/brack x86_64-darwin/brack-x86_64-darwin
          mv x86_64-darwin/brack-release x86_64-darwin/brack-release-x86_64-darwin
          mv aarch64-darwin/brack aarch64-darwin/brack-aarch64-darwin
          mv aarch64-darwin/brack-release aarch64-darwin/brack-release-aarch64-darwin
      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') }}
          generate_release_notes: true
          files: |
            x86_64-linux/brack-x86_64-linux
            x86_64-linux/brack-release-x86_64-linux
            x86_64-darwin/brack-x86_64-darwin
            x86_64-darwin/brack-release-x86_64-darwin
            aarch64-darwin/brack-aarch64-darwin
            aarch64-darwin/brack-release-aarch64-darwin

